# Generated by Django 5.0.1 on 2026-01-24 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_add_ai_tracking_models'),
        ('shared', '0002_add_projects_and_integrations'),
    ]

    operations = [
    ]
