# Migration to add all observability data models, cloud/cicd connections, and connection configs
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_add_project_api_keys'),
    ]

    operations = [
        # ---- APM / Metrics ----
        migrations.CreateModel(
            name='MetricDataPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=255)),
                ('metric_name', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('metric_type', models.CharField(default='gauge', max_length=20)),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_data_points', to='shared.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.tenant')),
            ],
            options={'db_table': 'obs_metric_data_points', 'ordering': ['-timestamp']},
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(db_index=True, max_length=128)),
                ('service_name', models.CharField(db_index=True, max_length=255)),
                ('endpoint', models.CharField(max_length=500)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('duration_ms', models.FloatField()),
                ('db_duration_ms', models.FloatField(default=0)),
                ('external_duration_ms', models.FloatField(default=0)),
                ('error', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='shared.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.tenant')),
            ],
            options={'db_table': 'obs_transactions', 'ordering': ['-timestamp']},
        ),

        # ---- Traces ----
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trace_id', models.CharField(db_index=True, max_length=128)),
                ('root_service', models.CharField(blank=True, default='', max_length=255)),
                ('root_operation', models.CharField(blank=True, default='', max_length=500)),
                ('duration_ms', models.FloatField(default=0)),
                ('span_count', models.IntegerField(default=0)),
                ('has_error', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traces', to='shared.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.tenant')),
            ],
            options={'db_table': 'obs_traces', 'ordering': ['-timestamp'], 'unique_together': {('project', 'trace_id')}},
        ),
        migrations.CreateModel(
            name='Span',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trace_id', models.CharField(db_index=True, max_length=128)),
                ('span_id', models.CharField(db_index=True, max_length=128)),
                ('parent_span_id', models.CharField(blank=True, default='', max_length=128)),
                ('service_name', models.CharField(max_length=255)),
                ('operation', models.CharField(max_length=500)),
                ('duration_ms', models.FloatField()),
                ('status', models.CharField(default='ok', max_length=20)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('events', models.JSONField(blank=True, default=list)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spans', to='shared.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.tenant')),
                ('trace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spans', to='shared.trace')),
            ],
            options={'db_table': 'obs_spans', 'ordering': ['-timestamp']},
        ),

        # ---- Errors ----
        migrations.CreateModel(
            name='ErrorGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(db_index=True, max_length=128)),
                ('service_name', models.CharField(max_length=255)),
                ('error_class', models.CharField(max_length=500)),
                ('message', models.TextField()),
                ('occurrence_count', models.IntegerField(default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='unresolved', max_length=20)),
                ('assignee', models.CharField(blank=True, default='', max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_groups', to='shared.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.tenant')),
            ],
            options={'db_table': 'obs_error_groups', 'ordering': ['-last_seen'], 'unique_together': {('project', 'fingerprint')}},
        ),
        migrations.CreateModel(
            name='ErrorOccurrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stack_trace', models.TextField(blank=True, default='')),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.tenant')),
                ('error_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='shared.errorgroup')),
            ],
            options={'db_table': 'obs_error_occurrences', 'ordering': ['-timestamp']},
        ),

        # ---- Infrastructure ----
        migrations.CreateModel(
            name='HostMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(db_index=True, max_length=255)),
                ('cpu_percent', models.FloatField(default=0)),
                ('memory_percent', models.FloatField(default=0)),
                ('disk_usage', models.JSONField(blank=True, default=dict)),
                ('network_io', models.JSONField(blank=True, default=dict)),
                ('load_avg', models.JSONField(blank=True, default=list)),
                ('processes', models.JSONField(blank=True, default=list)),
                ('containers', models.JSONField(blank=True, default=list)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_metrics', to='shared.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.tenant')),
            ],
            options={'db_table': 'obs_host_metrics', 'ordering': ['-timestamp']},
        ),

        # ---- Logs ----
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('level', models.CharField(db_index=True, max_length=20)),
                ('service_name', models.CharField(db_index=True, max_length=255)),
                ('message', models.TextField()),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('trace_id', models.CharField(blank=True, default='', max_length=128)),
                ('span_id', models.CharField(blank=True, default='', max_length=128)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='shared.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.tenant')),
            ],
            options={'db_table': 'obs_log_entries', 'ordering': ['-timestamp']},
        ),

        # ---- Deployments ----
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deployment_id', models.CharField(blank=True, default='', max_length=128)),
                ('service', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=128)),
                ('environment', models.CharField(default='production', max_length=50)),
                ('commit_sha', models.CharField(blank=True, default='', max_length=64)),
                ('commit_message', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('deployed_by', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(default='success', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(default='manual', max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='shared.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.tenant')),
            ],
            options={'db_table': 'obs_deployments', 'ordering': ['-started_at']},
        ),

        # ---- SLOs ----
        migrations.CreateModel(
            name='SLO',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('service_name', models.CharField(max_length=255)),
                ('sli_type', models.CharField(max_length=50)),
                ('target_percentage', models.FloatField()),
                ('time_window_days', models.IntegerField(default=30)),
                ('current_value', models.FloatField(default=100.0)),
                ('error_budget_remaining', models.FloatField(default=100.0)),
                ('status', models.CharField(default='met', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slos', to='shared.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.tenant')),
            ],
            options={'db_table': 'obs_slos', 'ordering': ['-created_at']},
        ),

        # ---- Dashboards ----
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('widgets', models.JSONField(blank=True, default=list)),
                ('variables', models.JSONField(blank=True, default=list)),
                ('layout', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='shared.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.tenant')),
            ],
            options={'db_table': 'obs_dashboards', 'ordering': ['-updated_at']},
        ),

        # ---- Alerting ----
        migrations.CreateModel(
            name='AlertPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_policies', to='shared.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.tenant')),
            ],
            options={'db_table': 'obs_alert_policies', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='AlertCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('condition_type', models.CharField(max_length=50)),
                ('metric_name', models.CharField(max_length=255)),
                ('service_name', models.CharField(blank=True, default='', max_length=255)),
                ('operator', models.CharField(max_length=10)),
                ('threshold', models.FloatField()),
                ('duration_minutes', models.IntegerField(default=5)),
                ('severity', models.CharField(default='warning', max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_conditions', to='shared.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.tenant')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conditions', to='shared.alertpolicy')),
            ],
            options={'db_table': 'obs_alert_conditions', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('channel_type', models.CharField(max_length=50)),
                ('config', models.JSONField(default=dict)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_channels', to='shared.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.tenant')),
                ('policies', models.ManyToManyField(blank=True, related_name='notification_channels', to='shared.alertpolicy')),
            ],
            options={'db_table': 'obs_notification_channels', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='ActiveAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('severity', models.CharField(default='warning', max_length=20)),
                ('status', models.CharField(default='firing', max_length=20)),
                ('service_name', models.CharField(blank=True, default='', max_length=255)),
                ('metric_value', models.FloatField(blank=True, null=True)),
                ('fired_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_alerts', to='shared.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.tenant')),
                ('condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_alerts', to='shared.alertcondition')),
            ],
            options={'db_table': 'obs_active_alerts', 'ordering': ['-fired_at']},
        ),
        migrations.CreateModel(
            name='MutingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('matchers', models.JSONField(default=dict)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muting_rules', to='shared.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.tenant')),
            ],
            options={'db_table': 'obs_muting_rules', 'ordering': ['-created_at']},
        ),

        # ---- Synthetic Monitoring ----
        migrations.CreateModel(
            name='SyntheticMonitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('monitor_type', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=1000)),
                ('frequency_seconds', models.IntegerField(default=300)),
                ('locations', models.JSONField(default=list)),
                ('config', models.JSONField(default=dict)),
                ('is_enabled', models.BooleanField(default=True)),
                ('status', models.CharField(default='unknown', max_length=20)),
                ('last_check_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synthetic_monitors', to='shared.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.tenant')),
            ],
            options={'db_table': 'obs_synthetic_monitors', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='SyntheticResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('success', models.BooleanField()),
                ('response_time_ms', models.FloatField()),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=50)),
                ('error_message', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.tenant')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='shared.syntheticmonitor')),
            ],
            options={'db_table': 'obs_synthetic_results', 'ordering': ['-timestamp']},
        ),

        # ---- Vulnerability ----
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cve_id', models.CharField(db_index=True, max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('severity', models.CharField(max_length=20)),
                ('service_name', models.CharField(max_length=255)),
                ('package_name', models.CharField(max_length=255)),
                ('installed_version', models.CharField(max_length=100)),
                ('fixed_version', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(default='open', max_length=20)),
                ('source', models.CharField(default='unknown', max_length=50)),
                ('first_detected', models.DateTimeField(auto_now_add=True)),
                ('last_detected', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='shared.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.tenant')),
            ],
            options={'db_table': 'obs_vulnerabilities', 'ordering': ['-last_detected'], 'unique_together': {('project', 'cve_id', 'service_name', 'package_name')}},
        ),

        # ---- Browser / RUM ----
        migrations.CreateModel(
            name='BrowserEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_name', models.CharField(blank=True, default='', max_length=255)),
                ('url', models.CharField(blank=True, default='', max_length=2000)),
                ('web_vitals', models.JSONField(blank=True, default=list)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('page_load', models.JSONField(blank=True, default=dict)),
                ('xhr_events', models.JSONField(blank=True, default=list)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browser_events', to='shared.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.tenant')),
            ],
            options={'db_table': 'obs_browser_events', 'ordering': ['-timestamp']},
        ),

        # ---- Service Registry ----
        migrations.CreateModel(
            name='ServiceRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=255)),
                ('service_type', models.CharField(default='backend', max_length=50)),
                ('language', models.CharField(blank=True, default='', max_length=50)),
                ('url', models.CharField(blank=True, default='', max_length=500)),
                ('health_check_path', models.CharField(blank=True, default='/health', max_length=200)),
                ('status', models.CharField(default='unknown', max_length=20)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(default='sdk', max_length=50)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_services', to='shared.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.tenant')),
            ],
            options={'db_table': 'obs_service_registrations', 'ordering': ['service_name'], 'unique_together': {('project', 'service_name')}},
        ),

        # ---- Cloud Connections ----
        migrations.CreateModel(
            name='CloudConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('azure', 'Azure'), ('aws', 'AWS'), ('gcp', 'GCP')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('credentials_encrypted', models.TextField(blank=True, default='')),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('connected', 'Connected'), ('error', 'Error'), ('syncing', 'Syncing')], default='pending', max_length=20)),
                ('status_message', models.TextField(blank=True, default='')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('resources_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_connections', to='shared.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.tenant')),
            ],
            options={'db_table': 'cloud_connections', 'ordering': ['-created_at']},
        ),

        # ---- CI/CD Connections ----
        migrations.CreateModel(
            name='CICDConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('azure_devops', 'Azure DevOps'), ('gitlab', 'GitLab'), ('jenkins', 'Jenkins'), ('bitbucket', 'Bitbucket')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('credentials_encrypted', models.TextField(blank=True, default='')),
                ('config', models.JSONField(blank=True, default=dict)),
                ('webhook_secret', models.CharField(blank=True, default='', max_length=128)),
                ('webhook_url', models.CharField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('connected', 'Connected'), ('error', 'Error')], default='pending', max_length=20)),
                ('status_message', models.TextField(blank=True, default='')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cicd_connections', to='shared.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.tenant')),
            ],
            options={'db_table': 'cicd_connections', 'ordering': ['-created_at']},
        ),

        # ---- Connection Config ----
        migrations.CreateModel(
            name='ConnectionConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('config_encrypted', models.TextField(blank=True, default='')),
                ('config_display', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_status', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_configs', to='shared.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.tenant')),
            ],
            options={'db_table': 'connection_configs', 'ordering': ['category', 'name']},
        ),
    ]
